import { revalidatePath } from "next/cache";
import { RealtimeRefresh } from "./realtime-refresh";
type Project = { id: string; name: string; description: string; status: string; progress: number };
type TaskStatus = "backlog" | "todo" | "in_progress" | "review" | "done";
type Task = { id: string; projectId: string; title: string; description: string; status: TaskStatus; priority: "low" | "medium" | "high" | "urgent"; assigneeId: string | null; dueDate: string | null };
type ActivityEvent = { id: string; projectId: string; actorId: string; type: "project.created" | "task.created" | "task.updated" | "task.completed"; message: string; createdAt: string };
const demoProjects: Project[] = [{ id:"demo-website",name:"Website relaunch",progress:72,description:"18 tasks in the current delivery cycle.",status:"On track"},{id:"demo-mobile",name:"Mobile onboarding",progress:46,description:"11 tasks in the current delivery cycle.",status:"Needs attention"},{id:"demo-analytics",name:"Analytics rollout",progress:88,description:"9 tasks in the current delivery cycle.",status:"On track"}];
const demoTaskMetrics={open:21,inProgress:7,completed:16};
const statuses:{value:TaskStatus;label:string}[]=[{value:"backlog",label:"Backlog"},{value:"todo",label:"To do"},{value:"in_progress",label:"In progress"},{value:"review",label:"Review"},{value:"done",label:"Done"}];
function getApiUrl(){return process.env.PULSEBOARD_API_URL??"http://localhost:4000"} function getPublicApiUrl(){return process.env.NEXT_PUBLIC_PULSEBOARD_API_URL??getApiUrl()}
async function loadProjects(){const r=await fetch(`${getApiUrl()}/projects`,{cache:"no-store"});if(!r.ok)throw new Error("Unable to load projects");return r.json() as Promise<Project[]>}
async function loadTasks(){const r=await fetch(`${getApiUrl()}/tasks`,{cache:"no-store"});if(!r.ok)throw new Error("Unable to load tasks");return r.json() as Promise<Task[]>}
async function loadActivity(){const r=await fetch(`${getApiUrl()}/activity?limit=8`,{cache:"no-store"});if(!r.ok)throw new Error("Unable to load activity");return r.json() as Promise<ActivityEvent[]>}
async function createProject(f:FormData){"use server";const name=String(f.get("name")??"").trim(),description=String(f.get("description")??"").trim();if(name.length<3||description.length<10)return;const r=await fetch(`${getApiUrl()}/projects`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,description})});if(!r.ok)throw new Error("Unable to create project");revalidatePath("/")}
async function createTask(f:FormData){"use server";const projectId=String(f.get("projectId")??"").trim(),title=String(f.get("title")??"").trim(),description=String(f.get("description")??"").trim(),priority=String(f.get("priority")??"medium"),assigneeId=String(f.get("assigneeId")??"").trim(),due=String(f.get("dueDate")??"").trim();if(!projectId||title.length<3||description.length<5||!["low","medium","high","urgent"].includes(priority))return;const r=await fetch(`${getApiUrl()}/tasks`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectId,title,description,priority,assigneeId:assigneeId||null,dueDate:due?new Date(due).toISOString():null})});if(!r.ok)throw new Error("Unable to create task");revalidatePath("/")}
async function updateTaskStatus(f:FormData){"use server";const taskId=String(f.get("taskId")??"").trim(),status=String(f.get("status")??"") as TaskStatus;if(!taskId||!statuses.some(o=>o.value===status))return;const r=await fetch(`${getApiUrl()}/tasks/${encodeURIComponent(taskId)}/status`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});if(!r.ok)throw new Error("Unable to update task status");revalidatePath("/")}
const fieldStyle={borderRadius:12,border:"1px solid rgba(148,163,184,.25)",background:"rgba(15,23,42,.72)",color:"inherit",padding:"0.85rem 1rem"};
export default async function HomePage({searchParams}:{searchParams:Promise<{project?:string;status?:string}>}){const params=await searchParams;let projects=demoProjects,sourceLabel="Demo workspace",apiAvailable=false,taskMetrics=demoTaskMetrics,recentTasks:Task[]=[],recentActivity:ActivityEvent[]=[];try{const [p,t,a]=await Promise.all([loadProjects(),loadTasks(),loadActivity()]);apiAvailable=true;projects=p;sourceLabel=p.length?"Live API data":"Live workspace - no projects yet";const completed=t.filter(x=>x.status==="done").length,inProgress=t.filter(x=>x.status==="in_progress"||x.status==="review").length;taskMetrics={open:t.length-completed,inProgress,completed};recentTasks=t.filter(x=>(!params.project||x.projectId===params.project)&&(!params.status||x.status===params.status)).slice(0,12);recentActivity=a}catch{sourceLabel="API offline - showing demo data"}
return <main className="shell"><header className="hero"><div><p className="eyebrow">PulseBoard</p><h1>Team execution at a glance.</h1><p className="lede">A collaborative workspace for projects, task ownership, live activity, and delivery analytics.</p></div><RealtimeRefresh apiUrl={getPublicApiUrl()}/></header>
{apiAvailable&&<section aria-labelledby="create-project-heading" style={{marginBottom:"2.5rem"}}><div className="sectionHeading"><div><p className="eyebrow">Quick create</p><h2 id="create-project-heading">Start a new project</h2></div></div><form action={createProject} style={{display:"grid",gridTemplateColumns:"minmax(180px,.8fr) minmax(260px,1.5fr) auto",gap:".75rem"}}><input name="name" minLength={3} maxLength={80} required placeholder="Project name" style={fieldStyle}/><input name="description" minLength={10} maxLength={500} required placeholder="What is this project delivering?" style={fieldStyle}/><button>Create project</button></form></section>}
{apiAvailable&&projects.length>0&&<section aria-labelledby="create-task-heading" style={{marginBottom:"2.5rem"}}><div className="sectionHeading"><div><p className="eyebrow">Add work</p><h2 id="create-task-heading">Create a task</h2></div><span>Assign ownership and a delivery target</span></div><form action={createTask} style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(180px,1fr))",gap:".75rem"}}><select name="projectId" required defaultValue="" style={fieldStyle}><option value="" disabled>Select project</option>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><input name="title" minLength={3} maxLength={120} required placeholder="Task title" style={fieldStyle}/><input name="description" minLength={5} maxLength={1000} required placeholder="Task description" style={fieldStyle}/><select name="priority" defaultValue="medium" style={fieldStyle}><option value="low">Low priority</option><option value="medium">Medium priority</option><option value="high">High priority</option><option value="urgent">Urgent</option></select><input name="assigneeId" maxLength={120} placeholder="Assignee (optional)" style={fieldStyle}/><input name="dueDate" type="datetime-local" style={fieldStyle}/><button>Add task</button></form></section>}
<section className="metrics"><article><strong>{projects.length}</strong><span>Visible projects</span></article><article><strong>{taskMetrics.open}</strong><span>Open tasks</span></article><article><strong>{taskMetrics.inProgress}</strong><span>In progress</span></article><article><strong>{taskMetrics.completed}</strong><span>Completed</span></article></section>
<section><div className="sectionHeading"><div><p className="eyebrow">Workspace</p><h2>Project pulse</h2></div><span>{sourceLabel}</span></div><div className="projectGrid">{projects.map(p=><article className="projectCard" key={p.id}><div className="projectMeta"><span>{p.status}</span><strong>{p.progress}%</strong></div><h3>{p.name}</h3><p>{p.description}</p><div className="progressTrack"><span style={{width:`${p.progress}%`}}/></div></article>)}</div></section>
{apiAvailable&&<section style={{marginTop:"2.5rem"}}><div className="sectionHeading"><div><p className="eyebrow">Task flow</p><h2>Work queue</h2></div><span>{recentTasks.length} matching tasks</span></div><form method="get" style={{display:"flex",gap:".75rem",marginBottom:"1rem",flexWrap:"wrap"}}><select name="project" defaultValue={params.project??""} style={fieldStyle}><option value="">All projects</option>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><select name="status" defaultValue={params.status??""} style={fieldStyle}><option value="">All statuses</option>{statuses.map(s=><option value={s.value} key={s.value}>{s.label}</option>)}</select><button>Filter tasks</button></form><div className="projectGrid">{recentTasks.map(t=><article className="projectCard" key={t.id}><div className="projectMeta"><span>{t.status.replaceAll("_"," ")}</span><strong>{t.priority}</strong></div><h3>{t.title}</h3><p>{t.description}</p><p><strong>Owner:</strong> {t.assigneeId??"Unassigned"}</p><p><strong>Due:</strong> {t.dueDate?new Date(t.dueDate).toLocaleString():"No due date"}</p><form action={updateTaskStatus} style={{display:"flex",gap:".5rem",marginTop:"1rem"}}><input type="hidden" name="taskId" value={t.id}/><select name="status" defaultValue={t.status} style={{...fieldStyle,flex:1}}>{statuses.map(s=><option key={s.value} value={s.value}>{s.label}</option>)}</select><button>Update</button></form></article>)}</div></section>}
{apiAvailable&&<section style={{marginTop:"2.5rem"}}><div className="sectionHeading"><div><p className="eyebrow">Activity</p><h2>Workspace timeline</h2></div><span>{recentActivity.length?`${recentActivity.length} latest events`:"No activity yet"}</span></div>{recentActivity.length>0&&<div className="projectGrid">{recentActivity.map(e=><article className="projectCard" key={e.id}><div className="projectMeta"><span>{e.type.replaceAll("."," ")}</span><strong>{projects.find(p=>p.id===e.projectId)?.name??"Workspace"}</strong></div><h3>{e.message}</h3><p>Actor: {e.actorId||"anonymous"}</p><p>{new Date(e.createdAt).toLocaleString()}</p></article>)}</div>}</section>}</main>}
