import cors from "cors";
import express, { type Request } from "express";
import { createServer } from "node:http";
import { Server } from "socket.io";
import { listActivity, recordActivity } from "./activity-store.js";
import { createProject, createProjectSchema, getProject, listProjects, syncProjectProgress } from "./projects.js";
import { createTask, createTaskSchema, deleteTask, listTasks, taskListQuerySchema, updateTask, updateTaskSchema, updateTaskStatus, updateTaskStatusSchema } from "./task-store.js";
const app=express(),httpServer=createServer(app),webOrigin=process.env.WEB_ORIGIN??"http://localhost:3000",io=new Server(httpServer,{cors:{origin:webOrigin}});app.use(cors({origin:webOrigin}));app.use(express.json());
function getActorId(request:Request){return request.header("x-actor-id")?.trim()||"system"}function publishActivity(event:ReturnType<typeof recordActivity>){io.emit("activity:created",event);return event}function refreshProjectPulse(projectId:string){const project=syncProjectProgress(projectId,listTasks({projectId}));if(project)io.emit("project:updated",project);return project}
app.get("/health",(_req,res)=>res.json({status:"ok",service:"pulseboard-api",realtime:true}));app.get("/projects",(_req,res)=>res.json(listProjects()));app.post("/projects",(req,res)=>{const parsed=createProjectSchema.safeParse(req.body);if(!parsed.success){res.status(400).json({error:"Invalid project payload",issues:parsed.error.issues});return}const project=createProject(parsed.data),activity=publishActivity(recordActivity({projectId:project.id,actorId:getActorId(req),type:"project.created",message:`Created project "${project.name}"`}));io.emit("project:created",project);res.status(201).json({...project,activity})});
app.get("/tasks",(req,res)=>{const parsed=taskListQuerySchema.safeParse(req.query);if(!parsed.success){res.status(400).json({error:"Invalid task filters",issues:parsed.error.issues});return}res.json(listTasks(parsed.data))});app.post("/tasks",(req,res)=>{const parsed=createTaskSchema.safeParse(req.body);if(!parsed.success){res.status(400).json({error:"Invalid task payload",issues:parsed.error.issues});return}if(!getProject(parsed.data.projectId)){res.status(404).json({error:"Project not found"});return}const task=createTask(parsed.data),project=refreshProjectPulse(task.projectId),activity=publishActivity(recordActivity({projectId:task.projectId,actorId:getActorId(req),type:"task.created",message:`Created task "${task.title}"`}));io.emit("task:created",task);res.status(201).json({...task,project,activity})});
app.patch("/tasks/:taskId",(req,res)=>{const parsed=updateTaskSchema.safeParse(req.body);if(!parsed.success){res.status(400).json({error:"Invalid task update",issues:parsed.error.issues});return}const task=updateTask(req.params.taskId,parsed.data);if(!task){res.status(404).json({error:"Task not found"});return}const project=refreshProjectPulse(task.projectId),activity=publishActivity(recordActivity({projectId:task.projectId,actorId:getActorId(req),type:"task.updated",message:`Updated task "${task.title}"`}));io.emit("task:updated",task);res.json({...task,project,activity})});app.patch("/tasks/:taskId/status",(req,res)=>{const parsed=updateTaskStatusSchema.safeParse(req.body);if(!parsed.success){res.status(400).json({error:"Invalid task status",issues:parsed.error.issues});return}const task=updateTaskStatus(req.params.taskId,parsed.data.status);if(!task){res.status(404).json({error:"Task not found"});return}const project=refreshProjectPulse(task.projectId),activity=publishActivity(recordActivity({projectId:task.projectId,actorId:getActorId(req),type:task.status==="done"?"task.completed":"task.updated",message:`Moved "${task.title}" to ${task.status.replaceAll("_"," ")}`}));io.emit("task:updated",task);res.json({...task,project,activity})});
app.delete("/tasks/:taskId",(req,res)=>{const task=deleteTask(req.params.taskId);if(!task){res.status(404).json({error:"Task not found"});return}const project=refreshProjectPulse(task.projectId),activity=publishActivity(recordActivity({projectId:task.projectId,actorId:getActorId(req),type:"task.updated",message:`Deleted task "${task.title}"`}));io.emit("task:deleted",{id:task.id,projectId:task.projectId});res.json({task,project,activity})});app.get("/activity",(req,res)=>{const projectId=typeof req.query.projectId==="string"?req.query.projectId:undefined,requestedLimit=Number(req.query.limit??50),limit=Number.isInteger(requestedLimit)?Math.min(Math.max(requestedLimit,1),100):50;res.json(listActivity(projectId,limit))});io.on("connection",socket=>socket.emit("workspace:ready",{message:"PulseBoard realtime channel connected"}));const port=Number(process.env.PORT??4000);httpServer.listen(port,()=>console.log(`PulseBoard API listening on port ${port}`));
